/**
 * SensorCard.jsx — Redesigned Sensor Dashboard
 *
 * Layout:
 *  - Top bar: title + live connection badge
 *  - Hero grid: 7 metric cards, each with:
 *      • Radial SVG gauge ring
 *      • Font Awesome icon
 *      • Animated numeric value
 *      • Status glow (good/warn/critical)
 *      • Optimal range bar
 *  - Bottom drawer: click any card to expand hardware specs
 *  - Empty state with animated pulse
 */
import React, { useState, useEffect, useRef } from 'react';
import '../styles/sensorcard.css';
import { getSensorRegistry, getStatusForValue, getSensorValue } from '../utils/sensorRegistry';

// ── Sensor meta-data ────────────────────────────────────────────────────────
const SENSORS = {
  soilMoisture: {
    label: 'Soil Moisture',  unit: '%',       faIcon: 'fa-droplet',
    color: '#22c55e',        maxDisplay: 100,
    hardware: { model: 'Capacitive Soil Moisture v1.2', type: 'Capacitive', range: '0–100%', voltage: '3.3V / 5V', output: 'Analog (0–3.3V)', accuracy: '±3%', description: 'Measures volumetric water content using capacitance. More durable than resistive sensors — no corrosion.' },
    optimal: { min: 20, max: 80 },
    status: v => v < 20 ? 'critical' : v < 40 ? 'warning' : 'good',
  },
  temperature: {
    label: 'Temperature',    unit: '°C',      faIcon: 'fa-temperature-half',
    color: '#f59e0b',        maxDisplay: 60,
    hardware: { model: 'DHT22 (AM2302)', type: 'Digital Temp + Humidity', range: '-40 to +80°C', voltage: '3.3V – 5.5V', output: 'Single-wire digital', accuracy: '±0.5°C', description: 'Combined temperature and humidity sensor. Uses single-wire protocol. Sampling rate: 0.5 Hz.' },
    optimal: { min: 15, max: 35 },
    status: v => v > 38 ? 'critical' : v > 32 ? 'warning' : 'good',
  },
  humidity: {
    label: 'Humidity',       unit: '%',       faIcon: 'fa-cloud-rain',
    color: '#22d3ee',        maxDisplay: 100,
    hardware: { model: 'DHT22 (AM2302)', type: 'Digital Temp + Humidity', range: '0–100% RH', voltage: '3.3V – 5.5V', output: 'Single-wire digital', accuracy: '±2% RH', description: 'Relative humidity measurement from the DHT22 sensor. Shared with temperature on the same IC.' },
    optimal: { min: 40, max: 80 },
    status: v => v < 30 ? 'warning' : 'good',
  },
  light: {
    label: 'Light Level',    unit: ' lux',    faIcon: 'fa-sun',
    color: '#fbbf24',        maxDisplay: 65535,
    hardware: { model: 'BH1750FVI', type: 'Ambient Light', range: '1–65535 lux', voltage: '2.4V – 3.6V', output: 'I²C (0x23 / 0x5C)', accuracy: '±20%', description: 'Digital ambient light sensor with 16-bit ADC. Directly outputs lux values. Ideal for plant light monitoring.' },
    optimal: { min: 1000, max: 50000 },
    status: v => v < 200 ? 'warning' : 'good',
  },
  pH: {
    label: 'Soil pH',        unit: '',        faIcon: 'fa-flask',
    color: '#a78bfa',        maxDisplay: 14,
    hardware: { model: 'Analog pH Electrode', type: 'Electrochemical', range: '0–14 pH', voltage: '5V', output: 'Analog (0–3.4V)', accuracy: '±0.1 pH', description: 'Glass electrode pH probe with BNC connector. Requires regular calibration with pH 4.0 / 7.0 / 10.0 buffer solutions.' },
    optimal: { min: 5.5, max: 7.0 },
    status: v => (v < 5.5 || v > 7.5) ? 'warning' : 'good',
  },
  flowRate: {
    label: 'Flow Rate',      unit: ' mL/min', faIcon: 'fa-faucet-drip',
    color: '#38bdf8',        maxDisplay: 900,
    hardware: { model: 'YF-S201 Hall Flow Sensor', type: 'Hall-effect Turbine', range: '1–30 L/min', voltage: '5V–18V', output: 'Pulse (digital)', accuracy: '±10%', description: 'Counts pulses generated by the turbine to estimate real-time flow rate. Verifies pump output and detects dry-run.' },
    optimal: { min: 10, max: 800 },
    status: v => v < 1 ? 'warning' : v > 900 ? 'critical' : 'good',
  },
  leafCount: {
    label: 'Leaf Count',     unit: ' leaves', faIcon: 'fa-seedling',
    color: '#34d399',        maxDisplay: 400,
    hardware: { model: 'ESP32-CAM + Edge Impulse', type: 'Computer Vision', range: '0–5000 leaves', voltage: '5V (ESP32-CAM)', output: 'AI-inferred integer', accuracy: 'Model-dependent', description: 'Estimated number of visible leaves from camera snapshots using the AI vision model.' },
    optimal: { min: 3, max: 400 },
    status: v => v <= 0 ? 'critical' : v < 3 ? 'warning' : 'good',
  },
};

const STATUS_CFG = {
  good:     { label: 'Normal',    color: '#22c55e', fa: 'fa-circle-check'    },
  warning:  { label: 'Attention', color: '#f59e0b', fa: 'fa-triangle-exclamation' },
  critical: { label: 'Critical',  color: '#ef4444', fa: 'fa-circle-exclamation' },
};

// ── Radial gauge ring (SVG) ─────────────────────────────────────────────────
function RadialGauge({ pct, color, status }) {
  const R = 36;
  const CIRC = 2 * Math.PI * R;
  const dash = Math.max(0, Math.min(1, pct)) * CIRC;
  const glowColor = STATUS_CFG[status]?.color || color;

  return (
    <svg className="sc-gauge-svg" viewBox="0 0 88 88" aria-hidden="true">
      {/* Track */}
      <circle cx="44" cy="44" r={R} fill="none" strokeWidth="6"
        stroke="rgba(255,255,255,0.07)" />
      {/* Fill */}
      <circle cx="44" cy="44" r={R} fill="none" strokeWidth="6"
        stroke={glowColor}
        strokeLinecap="round"
        strokeDasharray={`${dash} ${CIRC}`}
        strokeDashoffset={CIRC * 0.25}   /* start at 12 o'clock */
        style={{
          filter: `drop-shadow(0 0 6px ${glowColor}90)`,
          transition: 'stroke-dasharray 0.8s cubic-bezier(0.4,0,0.2,1)',
        }}
      />
    </svg>
  );
}

// ── Animated counter ────────────────────────────────────────────────────────
function AnimatedValue({ target, unit, decimals = 1 }) {
  const [display, setDisplay] = useState(target);
  const prev = useRef(target);

  useEffect(() => {
    if (target === prev.current) return;
    const start = prev.current;
    const end   = target;
    const dur   = 600;
    const t0    = performance.now();

    const step = (now) => {
      const p = Math.min((now - t0) / dur, 1);
      const ease = 1 - Math.pow(1 - p, 3);
      setDisplay(+(start + (end - start) * ease).toFixed(decimals));
      if (p < 1) requestAnimationFrame(step);
      else { setDisplay(end); prev.current = end; }
    };
    requestAnimationFrame(step);
  }, [target]);

  return <>{display}{unit}</>;
}

// ── Optimal range bar ───────────────────────────────────────────────────────
function RangeBar({ value, min, max, maxDisplay, color }) {
  const fullPct = Math.min(100, Math.max(0, (value / maxDisplay) * 100));
  const inRange = value >= min && value <= max;
  const barColor = inRange ? color : '#ef4444';
  // zone markers
  const minPct = (min / maxDisplay) * 100;
  const maxPct = (max / maxDisplay) * 100;

  return (
    <div className="sc-range-wrap">
      <div className="sc-range-track">
        {/* Optimal zone highlight */}
        <div className="sc-range-zone" style={{ left: `${minPct}%`, width: `${maxPct - minPct}%`, background: `${color}28` }} />
        {/* Value fill */}
        <div className="sc-range-fill" style={{ width: `${fullPct}%`, background: barColor, boxShadow: `0 0 8px ${barColor}70` }} />
      </div>
      <div className="sc-range-labels">
        <span>{min}{/* unit omitted for space */}</span>
        <span className="sc-range-optimal">optimal</span>
        <span>{max}</span>
      </div>
    </div>
  );
}

// ── Main metric card ────────────────────────────────────────────────────────
function HwDrawer({ hw, unit, optimal, color }) {
  const specs = [
    ['fa-tag', 'Model', hw.model],
    ['fa-microchip', 'Type', hw.type],
    ['fa-arrows-left-right', 'Range', hw.range],
    ['fa-bolt', 'Voltage', hw.voltage],
    ['fa-wave-square', 'Output', hw.output],
    ['fa-bullseye', 'Accuracy', hw.accuracy],
    ['fa-circle-check', 'Optimal', `${optimal.min}–${optimal.max}${unit}`],
  ];

  return (
    <div className="sc-drawer">
      <p className="sc-drawer-desc">{hw.description}</p>
      <div className="sc-drawer-specs">
        {specs.map(([icon, key, val]) => (
          <div key={key} className="sc-drawer-spec">
            <i className={`fa-solid ${icon} sc-spec-icon`} aria-hidden="true" style={{ color }} />
            <div>
              <div className="sc-spec-key">{key}</div>
              <div className="sc-spec-val">{val}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Main metric card ────────────────────────────────────────────────────────
function MetricCard({ info, value, isOpen, onToggle }) {
  const hasValue = value !== undefined && value !== null;
  const status   = hasValue ? info.status(value) : 'good';
  const pct      = hasValue ? Math.min(1, Math.max(0, value / info.maxDisplay)) : 0;
  const sc       = STATUS_CFG[status];
  const open = isOpen;

  const handleKeyDown = (event) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      onToggle();
    }
  };

  return (
    <div
      className={`sc-card sc-card--${status}${open ? ' sc-card--open' : ''}`}
      style={{ '--sc-color': info.color, '--sc-status-color': sc.color }}
      role="button"
      tabIndex={0}
      aria-expanded={open}
      onClick={onToggle}
      onKeyDown={handleKeyDown}
    >
      {/* ── Card header (always visible) ── */}
      <div className="sc-card-btn">

        {/* Gauge + icon */}
        <div className="sc-gauge-wrap">
          <RadialGauge pct={pct} color={info.color} status={status} />
          <i className={`fa-solid ${info.faIcon} sc-fa-icon`} aria-hidden="true" />
        </div>

        {/* Main info */}
        <div className="sc-card-body">
          <div className="sc-card-label">{info.label}</div>
          <div className="sc-card-value">
            {hasValue
              ? <AnimatedValue target={value} unit={info.unit} decimals={info.unit === ' lux' || info.unit === ' leaves' ? 0 : 1} />
              : <span className="sc-no-val">—</span>
            }
          </div>
          <div className="sc-card-model">{info.hardware.model}</div>
        </div>

        {/* Status badge + expand caret */}
        <div className="sc-card-right">
          <span className="sc-status-pill" style={{ background: `${sc.color}1a`, color: sc.color, borderColor: `${sc.color}40` }}>
            <i className={`fa-solid ${sc.fa}`} aria-hidden="true" />
            {sc.label}
          </span>
          <i className={`fa-solid fa-chevron-down sc-caret${open ? ' sc-caret--up' : ''}`} aria-hidden="true" />
        </div>
      </div>

      {/* Range bar */}
      {hasValue && (
        <div className="sc-range-row">
          <RangeBar value={value} min={info.optimal.min} max={info.optimal.max} maxDisplay={info.maxDisplay} color={info.color} />
        </div>
      )}

      {open && (
        <HwDrawer hw={info.hardware} unit={info.unit} optimal={info.optimal} color={info.color} />
      )}

    </div>
  );
}

// ── Connection dot ──────────────────────────────────────────────────────────
function ConnDot({ live }) {
  return (
    <span className={`sc-conn-badge${live ? '' : ' sc-conn-badge--off'}`}>
      <span className="sc-conn-dot" />
      <i className={`fa-solid ${live ? 'fa-wifi' : 'fa-wifi'} sc-conn-icon`} aria-hidden="true" />
      {live ? 'ESP32 Live' : 'No Signal'}
    </span>
  );
}

// ── Root export ─────────────────────────────────────────────────────────────
export function SensorCard({ sensors, isConnected }) {
  const [openedCardIndex, setOpenedCardIndex] = useState(null);
  const activeSensors = getSensorRegistry().filter(s => s.showInDashboard !== false && s.enabled !== false);

  const entries = activeSensors.map((s, index) => {
    const defaultVisuals = SENSORS[s.key] || {
      faIcon: 'fa-microchip',
      color: '#6366f1', // Indigo fallback
      hardware: { model: 'Custom Sensor', type: 'Generic', range: 'N/A', voltage: 'N/A', output: 'N/A', accuracy: 'N/A', description: 'User-defined custom sensor.' },
    };

    let value = undefined;
    if (sensors) {
      value = getSensorValue(sensors, s);
      if (value === null) value = undefined;
    }

    const maxThreshold = Number(s.maxThreshold) || 100;
    const warningThreshold = Number(s.warningThreshold) || maxThreshold;
    const minThreshold = Number(s.minThreshold) || 0;

    const info = {
      label: s.name,
      unit: s.unit || '',
      faIcon: s.faIcon || defaultVisuals.faIcon,
      color: s.color || defaultVisuals.color,
      maxDisplay: maxThreshold > 0 ? Math.ceil(maxThreshold * 1.2) : 100,
      hardware: defaultVisuals.hardware,
      optimal: { min: minThreshold, max: warningThreshold },
      status: (val) => {
        if (val === undefined || val === null) return 'good';
        const res = getStatusForValue(s, val);
        if (res.level === 'critical') return 'critical';
        if (res.level === 'warning') return 'warning';
        return 'good';
      },
    };

    const cardId = `${s.id || s.key || 'sensor'}-${index}`;
    return { cardId, cardIndex: index, info, value };
  });

  const liveCount = entries.filter(e => e.value !== undefined).length;

  return (
    <section className="sc-root">

      {/* ── Header ── */}
      <div className="sc-header">
        <div className="sc-header-left">
          <i className="fa-solid fa-gauge-high sc-header-icon" aria-hidden="true" />
          <div>
            <h2 className="sc-header-title">Live Sensor Data</h2>
            <p className="sc-header-sub">{liveCount} of {entries.length} sensors reporting</p>
          </div>
        </div>
        <ConnDot live={isConnected} />
      </div>

      {/* ── Sensor grid ── */}
      {entries.some(e => e.value !== undefined) || !sensors ? (
        <div className="sc-grid">
          {entries.map(({ cardId, cardIndex, info, value }) => (
            <MetricCard
              key={cardId}
              info={info}
              value={value}
              isOpen={openedCardIndex === cardIndex}
              onToggle={() => setOpenedCardIndex((prev) => (prev === cardIndex ? null : cardIndex))}
            />
          ))}
        </div>
      ) : (
        <div className="sc-empty">
          <div className="sc-empty-pulse" aria-hidden="true" />
          <i className="fa-solid fa-satellite-dish sc-empty-icon" aria-hidden="true" />
          <p className="sc-empty-text">Waiting for sensor data from ESP32…</p>
          <p className="sc-empty-hint">Ensure the device is powered and connected to Wi-Fi.</p>
        </div>
      )}

      <p className="sc-footer-hint">
        <i className="fa-solid fa-hand-pointer" aria-hidden="true" />
        &ensp;Tap any sensor card to open the details section.
      </p>
    </section>
  );
}
